title: "XXX"
description: "Data Engineering • Data Science • Analytics"
theme: jekyll-theme-minimal
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "Projects"
    link: /projects
markdown: kramdown
sass:
  style: compressed
include:
  - assets
